package com.itrus.ukey.sql;

import com.itrus.ukey.db.DomainSur;
import com.itrus.ukey.db.UserActionExample;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserActionExampleExt extends DomainSur {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_action
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_action
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_action
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    protected String searchFromPage;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_action
     *
     * @mbggenerated
     */
    public UserActionExampleExt() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_action
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_action
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_action
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_action
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_action
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }


    public String getSearchFromPage() {
        return searchFromPage;
    }

    public void setSearchFromPage(String searchFromPage) {
        this.searchFromPage = searchFromPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_action
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_action
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_action
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_action
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_action
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
        searchFromPage = null;
    }
    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_action
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ua.id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ua.id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ua.id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ua.id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ua.id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ua.id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ua.id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ua.id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ua.id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ua.id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andActionNameIsNull() {
            addCriterion("ua.action_name is null");
            return (Criteria) this;
        }

        public Criteria andActionNameIsNotNull() {
            addCriterion("ua.action_name is not null");
            return (Criteria) this;
        }

        public Criteria andActionNameEqualTo(String value) {
            addCriterion("ua.action_name =", value, "actionName");
            return (Criteria) this;
        }

        public Criteria andActionNameNotEqualTo(String value) {
            addCriterion("ua.action_name <>", value, "actionName");
            return (Criteria) this;
        }

        public Criteria andActionNameGreaterThan(String value) {
            addCriterion("ua.action_name >", value, "actionName");
            return (Criteria) this;
        }

        public Criteria andActionNameGreaterThanOrEqualTo(String value) {
            addCriterion("ua.action_name >=", value, "actionName");
            return (Criteria) this;
        }

        public Criteria andActionNameLessThan(String value) {
            addCriterion("ua.action_name <", value, "actionName");
            return (Criteria) this;
        }

        public Criteria andActionNameLessThanOrEqualTo(String value) {
            addCriterion("ua.action_name <=", value, "actionName");
            return (Criteria) this;
        }

        public Criteria andActionNameLike(String value) {
            addCriterion("ua.action_name like", value, "actionName");
            return (Criteria) this;
        }

        public Criteria andActionNameNotLike(String value) {
            addCriterion("ua.action_name not like", value, "actionName");
            return (Criteria) this;
        }

        public Criteria andActionNameIn(List<String> values) {
            addCriterion("ua.action_name in", values, "actionName");
            return (Criteria) this;
        }

        public Criteria andActionNameNotIn(List<String> values) {
            addCriterion("ua.action_name not in", values, "actionName");
            return (Criteria) this;
        }

        public Criteria andActionNameBetween(String value1, String value2) {
            addCriterion("ua.action_name between", value1, value2, "actionName");
            return (Criteria) this;
        }

        public Criteria andActionNameNotBetween(String value1, String value2) {
            addCriterion("ua.action_name not between", value1, value2, "actionName");
            return (Criteria) this;
        }

        public Criteria andActionTimeIsNull() {
            addCriterion("ua.action_time is null");
            return (Criteria) this;
        }

        public Criteria andActionTimeIsNotNull() {
            addCriterion("ua.action_time is not null");
            return (Criteria) this;
        }

        public Criteria andActionTimeEqualTo(Date value) {
            addCriterion("ua.action_time =", value, "actionTime");
            return (Criteria) this;
        }

        public Criteria andActionTimeNotEqualTo(Date value) {
            addCriterion("ua.action_time <>", value, "actionTime");
            return (Criteria) this;
        }

        public Criteria andActionTimeGreaterThan(Date value) {
            addCriterion("ua.action_time >", value, "actionTime");
            return (Criteria) this;
        }

        public Criteria andActionTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ua.action_time >=", value, "actionTime");
            return (Criteria) this;
        }

        public Criteria andActionTimeLessThan(Date value) {
            addCriterion("ua.action_time <", value, "actionTime");
            return (Criteria) this;
        }

        public Criteria andActionTimeLessThanOrEqualTo(Date value) {
            addCriterion("ua.action_time <=", value, "actionTime");
            return (Criteria) this;
        }

        public Criteria andActionTimeIn(List<Date> values) {
            addCriterion("ua.action_time in", values, "actionTime");
            return (Criteria) this;
        }

        public Criteria andActionTimeNotIn(List<Date> values) {
            addCriterion("ua.action_time not in", values, "actionTime");
            return (Criteria) this;
        }

        public Criteria andActionTimeBetween(Date value1, Date value2) {
            addCriterion("ua.action_time between", value1, value2, "actionTime");
            return (Criteria) this;
        }

        public Criteria andActionTimeNotBetween(Date value1, Date value2) {
            addCriterion("ua.action_time not between", value1, value2, "actionTime");
            return (Criteria) this;
        }
        public Criteria andCdLabelLike(String value) {
            addCriterion("cd.label like", value, "label");
            return (Criteria) this;
        }
        public Criteria andCertCnIsNull() {
            addCriterion("ua.cert_cn is null");
            return (Criteria) this;
        }

        public Criteria andCertCnIsNotNull() {
            addCriterion("ua.cert_cn is not null");
            return (Criteria) this;
        }

        public Criteria andCertCnEqualTo(String value) {
            addCriterion("ua.cert_cn =", value, "certCn");
            return (Criteria) this;
        }

        public Criteria andCertCnNotEqualTo(String value) {
            addCriterion("ua.cert_cn <>", value, "certCn");
            return (Criteria) this;
        }

        public Criteria andCertCnGreaterThan(String value) {
            addCriterion("ua.cert_cn >", value, "certCn");
            return (Criteria) this;
        }

        public Criteria andCertCnGreaterThanOrEqualTo(String value) {
            addCriterion("ua.cert_cn >=", value, "certCn");
            return (Criteria) this;
        }

        public Criteria andCertCnLessThan(String value) {
            addCriterion("ua.cert_cn <", value, "certCn");
            return (Criteria) this;
        }

        public Criteria andCertCnLessThanOrEqualTo(String value) {
            addCriterion("ua.cert_cn <=", value, "certCn");
            return (Criteria) this;
        }

        public Criteria andCertCnLike(String value) {
            addCriterion("ua.cert_cn like", value, "certCn");
            return (Criteria) this;
        }

        public Criteria andCertCnNotLike(String value) {
            addCriterion("ua.cert_cn not like", value, "certCn");
            return (Criteria) this;
        }

        public Criteria andCertCnIn(List<String> values) {
            addCriterion("ua.cert_cn in", values, "certCn");
            return (Criteria) this;
        }

        public Criteria andCertCnNotIn(List<String> values) {
            addCriterion("ua.cert_cn not in", values, "certCn");
            return (Criteria) this;
        }

        public Criteria andCertCnBetween(String value1, String value2) {
            addCriterion("ua.cert_cn between", value1, value2, "certCn");
            return (Criteria) this;
        }

        public Criteria andCertCnNotBetween(String value1, String value2) {
            addCriterion("ua.cert_cn not between", value1, value2, "certCn");
            return (Criteria) this;
        }

        public Criteria andClientTypeIsNull() {
            addCriterion("ua.client_type is null");
            return (Criteria) this;
        }

        public Criteria andClientTypeIsNotNull() {
            addCriterion("ua.client_type is not null");
            return (Criteria) this;
        }

        public Criteria andClientTypeEqualTo(Integer value) {
            addCriterion("ua.client_type =", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeEqualToCd() {
            addCriterion("ua.client_type = cd.client_type");
            return (Criteria) this;
        }

        public Criteria andClientTypeNotEqualTo(Integer value) {
            addCriterion("ua.client_type <>", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeGreaterThan(Integer value) {
            addCriterion("ua.client_type >", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ua.client_type >=", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeLessThan(Integer value) {
            addCriterion("ua.client_type <", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeLessThanOrEqualTo(Integer value) {
            addCriterion("ua.client_type <=", value, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeIn(List<Integer> values) {
            addCriterion("ua.client_type in", values, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeNotIn(List<Integer> values) {
            addCriterion("ua.client_type not in", values, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeBetween(Integer value1, Integer value2) {
            addCriterion("ua.client_type between", value1, value2, "clientType");
            return (Criteria) this;
        }

        public Criteria andClientTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("ua.client_type not between", value1, value2, "clientType");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("ua.create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("ua.create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("ua.create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("ua.create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("ua.create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("ua.create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("ua.create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("ua.create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("ua.create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("ua.create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("ua.create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("ua.create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andFromPageIsNull() {
            addCriterion("ua.from_page is null");
            return (Criteria) this;
        }

        public Criteria andFromPageIsNotNull() {
            addCriterion("ua.from_page is not null");
            return (Criteria) this;
        }

        public Criteria andFromPageEqualTo(String value) {
            addCriterion("ua.from_page =", value, "fromPage");
            return (Criteria) this;
        }

        public Criteria andFromPageEqualToCd() {
            addCriterion("ua.from_page = cd.dict_value");
            return (Criteria) this;
        }

        public Criteria andFromPageNotEqualTo(String value) {
            addCriterion("ua.from_page <>", value, "fromPage");
            return (Criteria) this;
        }

        public Criteria andFromPageGreaterThan(String value) {
            addCriterion("ua.from_page >", value, "fromPage");
            return (Criteria) this;
        }

        public Criteria andFromPageGreaterThanOrEqualTo(String value) {
            addCriterion("ua.from_page >=", value, "fromPage");
            return (Criteria) this;
        }

        public Criteria andFromPageLessThan(String value) {
            addCriterion("ua.from_page <", value, "fromPage");
            return (Criteria) this;
        }

        public Criteria andFromPageLessThanOrEqualTo(String value) {
            addCriterion("ua.from_page <=", value, "fromPage");
            return (Criteria) this;
        }

        public Criteria andFromPageLike(String value) {
            addCriterion("ua.from_page like", value, "fromPage");
            return (Criteria) this;
        }

        public Criteria andFromPageNotLike(String value) {
            addCriterion("ua.from_page not like", value, "fromPage");
            return (Criteria) this;
        }

        public Criteria andFromPageIn(List<String> values) {
            addCriterion("ua.from_page in", values, "fromPage");
            return (Criteria) this;
        }

        public Criteria andFromPageNotIn(List<String> values) {
            addCriterion("ua.from_page not in", values, "fromPage");
            return (Criteria) this;
        }

        public Criteria andFromPageBetween(String value1, String value2) {
            addCriterion("ua.from_page between", value1, value2, "fromPage");
            return (Criteria) this;
        }

        public Criteria andFromPageNotBetween(String value1, String value2) {
            addCriterion("ua.from_page not between", value1, value2, "fromPage");
            return (Criteria) this;
        }

        public Criteria andKeySnIsNull() {
            addCriterion("ua.key_sn is null");
            return (Criteria) this;
        }

        public Criteria andKeySnIsNotNull() {
            addCriterion("ua.key_sn is not null");
            return (Criteria) this;
        }

        public Criteria andKeySnEqualTo(String value) {
            addCriterion("ua.key_sn =", value, "keySn");
            return (Criteria) this;
        }

        public Criteria andKeySnNotEqualTo(String value) {
            addCriterion("ua.key_sn <>", value, "keySn");
            return (Criteria) this;
        }

        public Criteria andKeySnGreaterThan(String value) {
            addCriterion("ua.key_sn >", value, "keySn");
            return (Criteria) this;
        }

        public Criteria andKeySnGreaterThanOrEqualTo(String value) {
            addCriterion("ua.key_sn >=", value, "keySn");
            return (Criteria) this;
        }

        public Criteria andKeySnLessThan(String value) {
            addCriterion("ua.key_sn <", value, "keySn");
            return (Criteria) this;
        }

        public Criteria andKeySnLessThanOrEqualTo(String value) {
            addCriterion("ua.key_sn <=", value, "keySn");
            return (Criteria) this;
        }

        public Criteria andKeySnLike(String value) {
            addCriterion("ua.key_sn like", value, "keySn");
            return (Criteria) this;
        }

        public Criteria andKeySnNotLike(String value) {
            addCriterion("ua.key_sn not like", value, "keySn");
            return (Criteria) this;
        }

        public Criteria andKeySnIn(List<String> values) {
            addCriterion("ua.key_sn in", values, "keySn");
            return (Criteria) this;
        }

        public Criteria andKeySnNotIn(List<String> values) {
            addCriterion("ua.key_sn not in", values, "keySn");
            return (Criteria) this;
        }

        public Criteria andKeySnBetween(String value1, String value2) {
            addCriterion("ua.key_sn between", value1, value2, "keySn");
            return (Criteria) this;
        }

        public Criteria andKeySnNotBetween(String value1, String value2) {
            addCriterion("ua.key_sn not between", value1, value2, "keySn");
            return (Criteria) this;
        }

        public Criteria andModelCodeIsNull() {
            addCriterion("ua.model_code is null");
            return (Criteria) this;
        }

        public Criteria andModelCodeIsNotNull() {
            addCriterion("ua.model_code is not null");
            return (Criteria) this;
        }

        public Criteria andModelCodeEqualTo(Integer value) {
            addCriterion("ua.model_code =", value, "modelCode");
            return (Criteria) this;
        }

        public Criteria andModelCodeNotEqualTo(Integer value) {
            addCriterion("ua.model_code <>", value, "modelCode");
            return (Criteria) this;
        }

        public Criteria andModelCodeGreaterThan(Integer value) {
            addCriterion("ua.model_code >", value, "modelCode");
            return (Criteria) this;
        }

        public Criteria andModelCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("ua.model_code >=", value, "modelCode");
            return (Criteria) this;
        }

        public Criteria andModelCodeLessThan(Integer value) {
            addCriterion("ua.model_code <", value, "modelCode");
            return (Criteria) this;
        }

        public Criteria andModelCodeLessThanOrEqualTo(Integer value) {
            addCriterion("ua.model_code <=", value, "modelCode");
            return (Criteria) this;
        }

        public Criteria andModelCodeIn(List<Integer> values) {
            addCriterion("ua.model_code in", values, "modelCode");
            return (Criteria) this;
        }

        public Criteria andModelCodeNotIn(List<Integer> values) {
            addCriterion("ua.model_code not in", values, "modelCode");
            return (Criteria) this;
        }

        public Criteria andModelCodeBetween(Integer value1, Integer value2) {
            addCriterion("ua.model_code between", value1, value2, "modelCode");
            return (Criteria) this;
        }

        public Criteria andModelCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("ua.model_code not between", value1, value2, "modelCode");
            return (Criteria) this;
        }

        public Criteria andNowPageIsNull() {
            addCriterion("ua.now_page is null");
            return (Criteria) this;
        }

        public Criteria andNowPageIsNotNull() {
            addCriterion("ua.now_page is not null");
            return (Criteria) this;
        }

        public Criteria andNowPageEqualTo(String value) {
            addCriterion("ua.now_page =", value, "nowPage");
            return (Criteria) this;
        }
        public Criteria andNowPageEqualToCd() {
            addCriterion("ua.now_page = cd.dict_value");
            return (Criteria) this;
        }

        public Criteria andNowPageNotEqualTo(String value) {
            addCriterion("ua.now_page <>", value, "nowPage");
            return (Criteria) this;
        }

        public Criteria andNowPageGreaterThan(String value) {
            addCriterion("ua.now_page >", value, "nowPage");
            return (Criteria) this;
        }

        public Criteria andNowPageGreaterThanOrEqualTo(String value) {
            addCriterion("ua.now_page >=", value, "nowPage");
            return (Criteria) this;
        }

        public Criteria andNowPageLessThan(String value) {
            addCriterion("ua.now_page <", value, "nowPage");
            return (Criteria) this;
        }

        public Criteria andNowPageLessThanOrEqualTo(String value) {
            addCriterion("ua.now_page <=", value, "nowPage");
            return (Criteria) this;
        }

        public Criteria andNowPageLike(String value) {
            addCriterion("ua.now_page like", value, "nowPage");
            return (Criteria) this;
        }

        public Criteria andNowPageNotLike(String value) {
            addCriterion("ua.now_page not like", value, "nowPage");
            return (Criteria) this;
        }

        public Criteria andNowPageIn(List<String> values) {
            addCriterion("ua.now_page in", values, "nowPage");
            return (Criteria) this;
        }

        public Criteria andNowPageNotIn(List<String> values) {
            addCriterion("ua.now_page not in", values, "nowPage");
            return (Criteria) this;
        }

        public Criteria andNowPageBetween(String value1, String value2) {
            addCriterion("ua.now_page between", value1, value2, "nowPage");
            return (Criteria) this;
        }

        public Criteria andNowPageNotBetween(String value1, String value2) {
            addCriterion("ua.now_page not between", value1, value2, "nowPage");
            return (Criteria) this;
        }

        public Criteria andUserUidIsNull() {
            addCriterion("ua.user_uid is null");
            return (Criteria) this;
        }

        public Criteria andUserUidIsNotNull() {
            addCriterion("ua.user_uid is not null");
            return (Criteria) this;
        }

        public Criteria andUserUidEqualTo(String value) {
            addCriterion("ua.user_uid =", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidNotEqualTo(String value) {
            addCriterion("ua.user_uid <>", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidGreaterThan(String value) {
            addCriterion("ua.user_uid >", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidGreaterThanOrEqualTo(String value) {
            addCriterion("ua.user_uid >=", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidLessThan(String value) {
            addCriterion("ua.user_uid <", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidLessThanOrEqualTo(String value) {
            addCriterion("ua.user_uid <=", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidLike(String value) {
            addCriterion("ua.user_uid like", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidNotLike(String value) {
            addCriterion("ua.user_uid not like", value, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidIn(List<String> values) {
            addCriterion("ua.user_uid in", values, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidNotIn(List<String> values) {
            addCriterion("ua.user_uid not in", values, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidBetween(String value1, String value2) {
            addCriterion("ua.user_uid between", value1, value2, "userUid");
            return (Criteria) this;
        }

        public Criteria andUserUidNotBetween(String value1, String value2) {
            addCriterion("ua.user_uid not between", value1, value2, "userUid");
            return (Criteria) this;
        }

        public Criteria andVersionNumIsNull() {
            addCriterion("ua.version_num is null");
            return (Criteria) this;
        }

        public Criteria andVersionNumIsNotNull() {
            addCriterion("ua.version_num is not null");
            return (Criteria) this;
        }

        public Criteria andVersionNumEqualTo(Long value) {
            addCriterion("ua.version_num =", value, "versionNum");
            return (Criteria) this;
        }

        public Criteria andVersionNumNotEqualTo(Long value) {
            addCriterion("ua.version_num <>", value, "versionNum");
            return (Criteria) this;
        }

        public Criteria andVersionNumGreaterThan(Long value) {
            addCriterion("ua.version_num >", value, "versionNum");
            return (Criteria) this;
        }

        public Criteria andVersionNumGreaterThanOrEqualTo(Long value) {
            addCriterion("ua.version_num >=", value, "versionNum");
            return (Criteria) this;
        }

        public Criteria andVersionNumLessThan(Long value) {
            addCriterion("ua.version_num <", value, "versionNum");
            return (Criteria) this;
        }

        public Criteria andVersionNumLessThanOrEqualTo(Long value) {
            addCriterion("ua.version_num <=", value, "versionNum");
            return (Criteria) this;
        }

        public Criteria andVersionNumIn(List<Long> values) {
            addCriterion("ua.version_num in", values, "versionNum");
            return (Criteria) this;
        }

        public Criteria andVersionNumNotIn(List<Long> values) {
            addCriterion("ua.version_num not in", values, "versionNum");
            return (Criteria) this;
        }

        public Criteria andVersionNumBetween(Long value1, Long value2) {
            addCriterion("ua.version_num between", value1, value2, "versionNum");
            return (Criteria) this;
        }

        public Criteria andVersionNumBetweenCd() {
            addCriterion("ua.version_num between cd.start_ver_num and cd.end_ver_num");
            return (Criteria) this;
        }

        public Criteria andVersionNumNotBetween(Long value1, Long value2) {
            addCriterion("ua.version_num not between", value1, value2, "versionNum");
            return (Criteria) this;
        }

        public Criteria andVersionStrIsNull() {
            addCriterion("ua.version_str is null");
            return (Criteria) this;
        }

        public Criteria andVersionStrIsNotNull() {
            addCriterion("ua.version_str is not null");
            return (Criteria) this;
        }

        public Criteria andVersionStrEqualTo(String value) {
            addCriterion("ua.version_str =", value, "versionStr");
            return (Criteria) this;
        }

        public Criteria andVersionStrNotEqualTo(String value) {
            addCriterion("ua.version_str <>", value, "versionStr");
            return (Criteria) this;
        }

        public Criteria andVersionStrGreaterThan(String value) {
            addCriterion("ua.version_str >", value, "versionStr");
            return (Criteria) this;
        }

        public Criteria andVersionStrGreaterThanOrEqualTo(String value) {
            addCriterion("ua.version_str >=", value, "versionStr");
            return (Criteria) this;
        }

        public Criteria andVersionStrLessThan(String value) {
            addCriterion("ua.version_str <", value, "versionStr");
            return (Criteria) this;
        }

        public Criteria andVersionStrLessThanOrEqualTo(String value) {
            addCriterion("ua.version_str <=", value, "versionStr");
            return (Criteria) this;
        }

        public Criteria andVersionStrLike(String value) {
            addCriterion("ua.version_str like", value, "versionStr");
            return (Criteria) this;
        }

        public Criteria andVersionStrNotLike(String value) {
            addCriterion("ua.version_str not like", value, "versionStr");
            return (Criteria) this;
        }

        public Criteria andVersionStrIn(List<String> values) {
            addCriterion("ua.version_str in", values, "versionStr");
            return (Criteria) this;
        }

        public Criteria andVersionStrNotIn(List<String> values) {
            addCriterion("ua.version_str not in", values, "versionStr");
            return (Criteria) this;
        }

        public Criteria andVersionStrBetween(String value1, String value2) {
            addCriterion("ua.version_str between", value1, value2, "versionStr");
            return (Criteria) this;
        }

        public Criteria andVersionStrNotBetween(String value1, String value2) {
            addCriterion("ua.version_str not between", value1, value2, "versionStr");
            return (Criteria) this;
        }

        public Criteria andProjectIsNull() {
            addCriterion("ua.project is null");
            return (Criteria) this;
        }

        public Criteria andProjectIsNotNull() {
            addCriterion("ua.project is not null");
            return (Criteria) this;
        }

        public Criteria andProjectEqualTo(Long value) {
            addCriterion("ua.project =", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectNotEqualTo(Long value) {
            addCriterion("ua.project <>", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectGreaterThan(Long value) {
            addCriterion("ua.project >", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectGreaterThanOrEqualTo(Long value) {
            addCriterion("ua.project >=", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectLessThan(Long value) {
            addCriterion("ua.project <", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectLessThanOrEqualTo(Long value) {
            addCriterion("ua.project <=", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectIn(List<Long> values) {
            addCriterion("ua.project in", values, "project");
            return (Criteria) this;
        }

        public Criteria andProjectNotIn(List<Long> values) {
            addCriterion("ua.project not in", values, "project");
            return (Criteria) this;
        }

        public Criteria andProjectBetween(Long value1, Long value2) {
            addCriterion("ua.project between", value1, value2, "project");
            return (Criteria) this;
        }

        public Criteria andProjectNotBetween(Long value1, Long value2) {
            addCriterion("ua.project not between", value1, value2, "project");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_action
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_action
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}