package com.itrus.ukey.db;

import java.util.Date;

public class ActivityMsgTemp {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_msg_temp.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_msg_temp.cert_cn
     *
     * @mbggenerated
     */
    private String certCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_msg_temp.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_msg_temp.host_id
     *
     * @mbggenerated
     */
    private String hostId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_msg_temp.key_sn
     *
     * @mbggenerated
     */
    private String keySn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_msg_temp.life_time
     *
     * @mbggenerated
     */
    private Long lifeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_msg_temp.off_line_time
     *
     * @mbggenerated
     */
    private Date offLineTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_msg_temp.on_line_time
     *
     * @mbggenerated
     */
    private Date onLineTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_msg_temp.os_type
     *
     * @mbggenerated
     */
    private String osType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_msg_temp.process_id
     *
     * @mbggenerated
     */
    private String processId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_msg_temp.thread_id
     *
     * @mbggenerated
     */
    private String threadId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_msg_temp.ukey_version
     *
     * @mbggenerated
     */
    private String ukeyVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column activity_msg_temp.project
     *
     * @mbggenerated
     */
    private Long project;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_msg_temp.id
     *
     * @return the value of activity_msg_temp.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_msg_temp.id
     *
     * @param id the value for activity_msg_temp.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_msg_temp.cert_cn
     *
     * @return the value of activity_msg_temp.cert_cn
     *
     * @mbggenerated
     */
    public String getCertCn() {
        return certCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_msg_temp.cert_cn
     *
     * @param certCn the value for activity_msg_temp.cert_cn
     *
     * @mbggenerated
     */
    public void setCertCn(String certCn) {
        this.certCn = certCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_msg_temp.create_time
     *
     * @return the value of activity_msg_temp.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_msg_temp.create_time
     *
     * @param createTime the value for activity_msg_temp.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_msg_temp.host_id
     *
     * @return the value of activity_msg_temp.host_id
     *
     * @mbggenerated
     */
    public String getHostId() {
        return hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_msg_temp.host_id
     *
     * @param hostId the value for activity_msg_temp.host_id
     *
     * @mbggenerated
     */
    public void setHostId(String hostId) {
        this.hostId = hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_msg_temp.key_sn
     *
     * @return the value of activity_msg_temp.key_sn
     *
     * @mbggenerated
     */
    public String getKeySn() {
        return keySn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_msg_temp.key_sn
     *
     * @param keySn the value for activity_msg_temp.key_sn
     *
     * @mbggenerated
     */
    public void setKeySn(String keySn) {
        this.keySn = keySn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_msg_temp.life_time
     *
     * @return the value of activity_msg_temp.life_time
     *
     * @mbggenerated
     */
    public Long getLifeTime() {
        return lifeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_msg_temp.life_time
     *
     * @param lifeTime the value for activity_msg_temp.life_time
     *
     * @mbggenerated
     */
    public void setLifeTime(Long lifeTime) {
        this.lifeTime = lifeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_msg_temp.off_line_time
     *
     * @return the value of activity_msg_temp.off_line_time
     *
     * @mbggenerated
     */
    public Date getOffLineTime() {
        return offLineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_msg_temp.off_line_time
     *
     * @param offLineTime the value for activity_msg_temp.off_line_time
     *
     * @mbggenerated
     */
    public void setOffLineTime(Date offLineTime) {
        this.offLineTime = offLineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_msg_temp.on_line_time
     *
     * @return the value of activity_msg_temp.on_line_time
     *
     * @mbggenerated
     */
    public Date getOnLineTime() {
        return onLineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_msg_temp.on_line_time
     *
     * @param onLineTime the value for activity_msg_temp.on_line_time
     *
     * @mbggenerated
     */
    public void setOnLineTime(Date onLineTime) {
        this.onLineTime = onLineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_msg_temp.os_type
     *
     * @return the value of activity_msg_temp.os_type
     *
     * @mbggenerated
     */
    public String getOsType() {
        return osType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_msg_temp.os_type
     *
     * @param osType the value for activity_msg_temp.os_type
     *
     * @mbggenerated
     */
    public void setOsType(String osType) {
        this.osType = osType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_msg_temp.process_id
     *
     * @return the value of activity_msg_temp.process_id
     *
     * @mbggenerated
     */
    public String getProcessId() {
        return processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_msg_temp.process_id
     *
     * @param processId the value for activity_msg_temp.process_id
     *
     * @mbggenerated
     */
    public void setProcessId(String processId) {
        this.processId = processId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_msg_temp.thread_id
     *
     * @return the value of activity_msg_temp.thread_id
     *
     * @mbggenerated
     */
    public String getThreadId() {
        return threadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_msg_temp.thread_id
     *
     * @param threadId the value for activity_msg_temp.thread_id
     *
     * @mbggenerated
     */
    public void setThreadId(String threadId) {
        this.threadId = threadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_msg_temp.ukey_version
     *
     * @return the value of activity_msg_temp.ukey_version
     *
     * @mbggenerated
     */
    public String getUkeyVersion() {
        return ukeyVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_msg_temp.ukey_version
     *
     * @param ukeyVersion the value for activity_msg_temp.ukey_version
     *
     * @mbggenerated
     */
    public void setUkeyVersion(String ukeyVersion) {
        this.ukeyVersion = ukeyVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column activity_msg_temp.project
     *
     * @return the value of activity_msg_temp.project
     *
     * @mbggenerated
     */
    public Long getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column activity_msg_temp.project
     *
     * @param project the value for activity_msg_temp.project
     *
     * @mbggenerated
     */
    public void setProject(Long project) {
        this.project = project;
    }
}