package com.itrus.ukey.db;

public class AdminRole {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin_role.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin_role.role_describe
	 * @mbggenerated
	 */
	private String roleDescribe;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column admin_role.role_name
	 * @mbggenerated
	 */
	private String roleName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin_role.id
	 * @return  the value of admin_role.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin_role.id
	 * @param id  the value for admin_role.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin_role.role_describe
	 * @return  the value of admin_role.role_describe
	 * @mbggenerated
	 */
	public String getRoleDescribe() {
		return roleDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin_role.role_describe
	 * @param roleDescribe  the value for admin_role.role_describe
	 * @mbggenerated
	 */
	public void setRoleDescribe(String roleDescribe) {
		this.roleDescribe = roleDescribe;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column admin_role.role_name
	 * @return  the value of admin_role.role_name
	 * @mbggenerated
	 */
	public String getRoleName() {
		return roleName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column admin_role.role_name
	 * @param roleName  the value for admin_role.role_name
	 * @mbggenerated
	 */
	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}
}