package com.itrus.ukey.db;

public class LicenseWithBLOBs extends License {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column license.license_data
	 * @mbggenerated
	 */
	private byte[] licenseData;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column license.license_sign
	 * @mbggenerated
	 */
	private byte[] licenseSign;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column license.license_data
	 * @return  the value of license.license_data
	 * @mbggenerated
	 */
	public byte[] getLicenseData() {
		return licenseData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column license.license_data
	 * @param licenseData  the value for license.license_data
	 * @mbggenerated
	 */
	public void setLicenseData(byte[] licenseData) {
		this.licenseData = licenseData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column license.license_sign
	 * @return  the value of license.license_sign
	 * @mbggenerated
	 */
	public byte[] getLicenseSign() {
		return licenseSign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column license.license_sign
	 * @param licenseSign  the value for license.license_sign
	 * @mbggenerated
	 */
	public void setLicenseSign(byte[] licenseSign) {
		this.licenseSign = licenseSign;
	}
}