package com.itrus.ukey.db;

import java.util.Date;

public class License {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column license.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column license.android
	 * @mbggenerated
	 */
	private Integer android;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column license.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column license.ios
	 * @mbggenerated
	 */
	private Integer ios;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column license.org_code
	 * @mbggenerated
	 */
	private String orgCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column license.status
	 * @mbggenerated
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column license.win
	 * @mbggenerated
	 */
	private Integer win;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column license.end_time
	 * @mbggenerated
	 */
	private Date endTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column license.id
	 * @return  the value of license.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column license.id
	 * @param id  the value for license.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column license.android
	 * @return  the value of license.android
	 * @mbggenerated
	 */
	public Integer getAndroid() {
		return android;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column license.android
	 * @param android  the value for license.android
	 * @mbggenerated
	 */
	public void setAndroid(Integer android) {
		this.android = android;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column license.create_time
	 * @return  the value of license.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column license.create_time
	 * @param createTime  the value for license.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column license.ios
	 * @return  the value of license.ios
	 * @mbggenerated
	 */
	public Integer getIos() {
		return ios;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column license.ios
	 * @param ios  the value for license.ios
	 * @mbggenerated
	 */
	public void setIos(Integer ios) {
		this.ios = ios;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column license.org_code
	 * @return  the value of license.org_code
	 * @mbggenerated
	 */
	public String getOrgCode() {
		return orgCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column license.org_code
	 * @param orgCode  the value for license.org_code
	 * @mbggenerated
	 */
	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column license.status
	 * @return  the value of license.status
	 * @mbggenerated
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column license.status
	 * @param status  the value for license.status
	 * @mbggenerated
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column license.win
	 * @return  the value of license.win
	 * @mbggenerated
	 */
	public Integer getWin() {
		return win;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column license.win
	 * @param win  the value for license.win
	 * @mbggenerated
	 */
	public void setWin(Integer win) {
		this.win = win;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column license.end_time
	 * @return  the value of license.end_time
	 * @mbggenerated
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column license.end_time
	 * @param endTime  the value for license.end_time
	 * @mbggenerated
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}
}