package com.itrus.ukey.db;

import java.util.Date;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.authapp
     *
     * @mbggenerated
     */
    private String authapp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.config_item
     *
     * @mbggenerated
     */
    private String configItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.detail
     *
     * @mbggenerated
     */
    private String detail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.is_key
     *
     * @mbggenerated
     */
    private String isKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.is_login
     *
     * @mbggenerated
     */
    private String isLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.is_show_on_key
     *
     * @mbggenerated
     */
    private Boolean isShowOnKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.is_show_on_login
     *
     * @mbggenerated
     */
    private Boolean isShowOnLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.is_show_on_start
     *
     * @mbggenerated
     */
    private Boolean isShowOnStart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.link
     *
     * @mbggenerated
     */
    private String link;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.publish_time
     *
     * @mbggenerated
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.show_times
     *
     * @mbggenerated
     */
    private String showTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.show_end_time
     *
     * @mbggenerated
     */
    private Date showEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.show_start_time
     *
     * @mbggenerated
     */
    private Date showStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.un_authapp
     *
     * @mbggenerated
     */
    private String unAuthapp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.project
     *
     * @mbggenerated
     */
    private Long project;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.has_config
     *
     * @mbggenerated
     */
    private String hasConfig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.no_config
     *
     * @mbggenerated
     */
    private String noConfig;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.params
     *
     * @mbggenerated
     */
    private String params;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.photo
     *
     * @mbggenerated
     */
    private byte[] photo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.authapp
     *
     * @return the value of message.authapp
     *
     * @mbggenerated
     */
    public String getAuthapp() {
        return authapp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.authapp
     *
     * @param authapp the value for message.authapp
     *
     * @mbggenerated
     */
    public void setAuthapp(String authapp) {
        this.authapp = authapp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.config_item
     *
     * @return the value of message.config_item
     *
     * @mbggenerated
     */
    public String getConfigItem() {
        return configItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.config_item
     *
     * @param configItem the value for message.config_item
     *
     * @mbggenerated
     */
    public void setConfigItem(String configItem) {
        this.configItem = configItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.create_time
     *
     * @return the value of message.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.create_time
     *
     * @param createTime the value for message.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.detail
     *
     * @return the value of message.detail
     *
     * @mbggenerated
     */
    public String getDetail() {
        return detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.detail
     *
     * @param detail the value for message.detail
     *
     * @mbggenerated
     */
    public void setDetail(String detail) {
        this.detail = detail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.is_key
     *
     * @return the value of message.is_key
     *
     * @mbggenerated
     */
    public String getIsKey() {
        return isKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.is_key
     *
     * @param isKey the value for message.is_key
     *
     * @mbggenerated
     */
    public void setIsKey(String isKey) {
        this.isKey = isKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.is_login
     *
     * @return the value of message.is_login
     *
     * @mbggenerated
     */
    public String getIsLogin() {
        return isLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.is_login
     *
     * @param isLogin the value for message.is_login
     *
     * @mbggenerated
     */
    public void setIsLogin(String isLogin) {
        this.isLogin = isLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.is_show_on_key
     *
     * @return the value of message.is_show_on_key
     *
     * @mbggenerated
     */
    public Boolean getIsShowOnKey() {
        return isShowOnKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.is_show_on_key
     *
     * @param isShowOnKey the value for message.is_show_on_key
     *
     * @mbggenerated
     */
    public void setIsShowOnKey(Boolean isShowOnKey) {
        this.isShowOnKey = isShowOnKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.is_show_on_login
     *
     * @return the value of message.is_show_on_login
     *
     * @mbggenerated
     */
    public Boolean getIsShowOnLogin() {
        return isShowOnLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.is_show_on_login
     *
     * @param isShowOnLogin the value for message.is_show_on_login
     *
     * @mbggenerated
     */
    public void setIsShowOnLogin(Boolean isShowOnLogin) {
        this.isShowOnLogin = isShowOnLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.is_show_on_start
     *
     * @return the value of message.is_show_on_start
     *
     * @mbggenerated
     */
    public Boolean getIsShowOnStart() {
        return isShowOnStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.is_show_on_start
     *
     * @param isShowOnStart the value for message.is_show_on_start
     *
     * @mbggenerated
     */
    public void setIsShowOnStart(Boolean isShowOnStart) {
        this.isShowOnStart = isShowOnStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.link
     *
     * @return the value of message.link
     *
     * @mbggenerated
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.link
     *
     * @param link the value for message.link
     *
     * @mbggenerated
     */
    public void setLink(String link) {
        this.link = link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.publish_time
     *
     * @return the value of message.publish_time
     *
     * @mbggenerated
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.publish_time
     *
     * @param publishTime the value for message.publish_time
     *
     * @mbggenerated
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.show_times
     *
     * @return the value of message.show_times
     *
     * @mbggenerated
     */
    public String getShowTimes() {
        return showTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.show_times
     *
     * @param showTimes the value for message.show_times
     *
     * @mbggenerated
     */
    public void setShowTimes(String showTimes) {
        this.showTimes = showTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.show_end_time
     *
     * @return the value of message.show_end_time
     *
     * @mbggenerated
     */
    public Date getShowEndTime() {
        return showEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.show_end_time
     *
     * @param showEndTime the value for message.show_end_time
     *
     * @mbggenerated
     */
    public void setShowEndTime(Date showEndTime) {
        this.showEndTime = showEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.show_start_time
     *
     * @return the value of message.show_start_time
     *
     * @mbggenerated
     */
    public Date getShowStartTime() {
        return showStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.show_start_time
     *
     * @param showStartTime the value for message.show_start_time
     *
     * @mbggenerated
     */
    public void setShowStartTime(Date showStartTime) {
        this.showStartTime = showStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.status
     *
     * @return the value of message.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.status
     *
     * @param status the value for message.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.title
     *
     * @return the value of message.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.title
     *
     * @param title the value for message.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.un_authapp
     *
     * @return the value of message.un_authapp
     *
     * @mbggenerated
     */
    public String getUnAuthapp() {
        return unAuthapp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.un_authapp
     *
     * @param unAuthapp the value for message.un_authapp
     *
     * @mbggenerated
     */
    public void setUnAuthapp(String unAuthapp) {
        this.unAuthapp = unAuthapp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.project
     *
     * @return the value of message.project
     *
     * @mbggenerated
     */
    public Long getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.project
     *
     * @param project the value for message.project
     *
     * @mbggenerated
     */
    public void setProject(Long project) {
        this.project = project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.has_config
     *
     * @return the value of message.has_config
     *
     * @mbggenerated
     */
    public String getHasConfig() {
        return hasConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.has_config
     *
     * @param hasConfig the value for message.has_config
     *
     * @mbggenerated
     */
    public void setHasConfig(String hasConfig) {
        this.hasConfig = hasConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.no_config
     *
     * @return the value of message.no_config
     *
     * @mbggenerated
     */
    public String getNoConfig() {
        return noConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.no_config
     *
     * @param noConfig the value for message.no_config
     *
     * @mbggenerated
     */
    public void setNoConfig(String noConfig) {
        this.noConfig = noConfig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.params
     *
     * @return the value of message.params
     *
     * @mbggenerated
     */
    public String getParams() {
        return params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.params
     *
     * @param params the value for message.params
     *
     * @mbggenerated
     */
    public void setParams(String params) {
        this.params = params;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.photo
     *
     * @return the value of message.photo
     *
     * @mbggenerated
     */
    public byte[] getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.photo
     *
     * @param photo the value for message.photo
     *
     * @mbggenerated
     */
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
}