package com.itrus.ukey.db;

public class PlatformWithBLOBs extends Platform {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.logo1
     *
     * @mbggenerated
     */
    private byte[] logo1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.logo2
     *
     * @mbggenerated
     */
    private byte[] logo2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column platform.logov4
     *
     * @mbggenerated
     */
    private byte[] logov4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.logo1
     *
     * @return the value of platform.logo1
     *
     * @mbggenerated
     */
    public byte[] getLogo1() {
        return logo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.logo1
     *
     * @param logo1 the value for platform.logo1
     *
     * @mbggenerated
     */
    public void setLogo1(byte[] logo1) {
        this.logo1 = logo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.logo2
     *
     * @return the value of platform.logo2
     *
     * @mbggenerated
     */
    public byte[] getLogo2() {
        return logo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.logo2
     *
     * @param logo2 the value for platform.logo2
     *
     * @mbggenerated
     */
    public void setLogo2(byte[] logo2) {
        this.logo2 = logo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column platform.logov4
     *
     * @return the value of platform.logov4
     *
     * @mbggenerated
     */
    public byte[] getLogov4() {
        return logov4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column platform.logov4
     *
     * @param logov4 the value for platform.logov4
     *
     * @mbggenerated
     */
    public void setLogov4(byte[] logov4) {
        this.logov4 = logov4;
    }
}