package com.itrus.ukey.db;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProjectVersionExample extends DomainSur {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_version
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_version
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project_version
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_version
     *
     * @mbggenerated
     */
    public ProjectVersionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_version
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_version
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_version
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_version
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_version
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_version
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_version
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_version
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_version
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_version
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_version
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andIsPushIsNull() {
            addCriterion("is_push is null");
            return (Criteria) this;
        }

        public Criteria andIsPushIsNotNull() {
            addCriterion("is_push is not null");
            return (Criteria) this;
        }

        public Criteria andIsPushEqualTo(Boolean value) {
            addCriterion("is_push =", value, "isPush");
            return (Criteria) this;
        }

        public Criteria andIsPushNotEqualTo(Boolean value) {
            addCriterion("is_push <>", value, "isPush");
            return (Criteria) this;
        }

        public Criteria andIsPushGreaterThan(Boolean value) {
            addCriterion("is_push >", value, "isPush");
            return (Criteria) this;
        }

        public Criteria andIsPushGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_push >=", value, "isPush");
            return (Criteria) this;
        }

        public Criteria andIsPushLessThan(Boolean value) {
            addCriterion("is_push <", value, "isPush");
            return (Criteria) this;
        }

        public Criteria andIsPushLessThanOrEqualTo(Boolean value) {
            addCriterion("is_push <=", value, "isPush");
            return (Criteria) this;
        }

        public Criteria andIsPushIn(List<Boolean> values) {
            addCriterion("is_push in", values, "isPush");
            return (Criteria) this;
        }

        public Criteria andIsPushNotIn(List<Boolean> values) {
            addCriterion("is_push not in", values, "isPush");
            return (Criteria) this;
        }

        public Criteria andIsPushBetween(Boolean value1, Boolean value2) {
            addCriterion("is_push between", value1, value2, "isPush");
            return (Criteria) this;
        }

        public Criteria andIsPushNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_push not between", value1, value2, "isPush");
            return (Criteria) this;
        }

        public Criteria andProductVersionIsNull() {
            addCriterion("product_version is null");
            return (Criteria) this;
        }

        public Criteria andProductVersionIsNotNull() {
            addCriterion("product_version is not null");
            return (Criteria) this;
        }

        public Criteria andProductVersionEqualTo(Long value) {
            addCriterion("product_version =", value, "productVersion");
            return (Criteria) this;
        }

        public Criteria andProductVersionNotEqualTo(Long value) {
            addCriterion("product_version <>", value, "productVersion");
            return (Criteria) this;
        }

        public Criteria andProductVersionGreaterThan(Long value) {
            addCriterion("product_version >", value, "productVersion");
            return (Criteria) this;
        }

        public Criteria andProductVersionGreaterThanOrEqualTo(Long value) {
            addCriterion("product_version >=", value, "productVersion");
            return (Criteria) this;
        }

        public Criteria andProductVersionLessThan(Long value) {
            addCriterion("product_version <", value, "productVersion");
            return (Criteria) this;
        }

        public Criteria andProductVersionLessThanOrEqualTo(Long value) {
            addCriterion("product_version <=", value, "productVersion");
            return (Criteria) this;
        }

        public Criteria andProductVersionIn(List<Long> values) {
            addCriterion("product_version in", values, "productVersion");
            return (Criteria) this;
        }

        public Criteria andProductVersionNotIn(List<Long> values) {
            addCriterion("product_version not in", values, "productVersion");
            return (Criteria) this;
        }

        public Criteria andProductVersionBetween(Long value1, Long value2) {
            addCriterion("product_version between", value1, value2, "productVersion");
            return (Criteria) this;
        }

        public Criteria andProductVersionNotBetween(Long value1, Long value2) {
            addCriterion("product_version not between", value1, value2, "productVersion");
            return (Criteria) this;
        }

        public Criteria andProjectIsNull() {
            addCriterion("project is null");
            return (Criteria) this;
        }

        public Criteria andProjectIsNotNull() {
            addCriterion("project is not null");
            return (Criteria) this;
        }

        public Criteria andProjectEqualTo(Long value) {
            addCriterion("project =", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectNotEqualTo(Long value) {
            addCriterion("project <>", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectGreaterThan(Long value) {
            addCriterion("project >", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectGreaterThanOrEqualTo(Long value) {
            addCriterion("project >=", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectLessThan(Long value) {
            addCriterion("project <", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectLessThanOrEqualTo(Long value) {
            addCriterion("project <=", value, "project");
            return (Criteria) this;
        }

        public Criteria andProjectIn(List<Long> values) {
            addCriterion("project in", values, "project");
            return (Criteria) this;
        }

        public Criteria andProjectNotIn(List<Long> values) {
            addCriterion("project not in", values, "project");
            return (Criteria) this;
        }

        public Criteria andProjectBetween(Long value1, Long value2) {
            addCriterion("project between", value1, value2, "project");
            return (Criteria) this;
        }

        public Criteria andProjectNotBetween(Long value1, Long value2) {
            addCriterion("project not between", value1, value2, "project");
            return (Criteria) this;
        }

        public Criteria andMinVersionIsNull() {
            addCriterion("min_version is null");
            return (Criteria) this;
        }

        public Criteria andMinVersionIsNotNull() {
            addCriterion("min_version is not null");
            return (Criteria) this;
        }

        public Criteria andMinVersionEqualTo(String value) {
            addCriterion("min_version =", value, "minVersion");
            return (Criteria) this;
        }

        public Criteria andMinVersionNotEqualTo(String value) {
            addCriterion("min_version <>", value, "minVersion");
            return (Criteria) this;
        }

        public Criteria andMinVersionGreaterThan(String value) {
            addCriterion("min_version >", value, "minVersion");
            return (Criteria) this;
        }

        public Criteria andMinVersionGreaterThanOrEqualTo(String value) {
            addCriterion("min_version >=", value, "minVersion");
            return (Criteria) this;
        }

        public Criteria andMinVersionLessThan(String value) {
            addCriterion("min_version <", value, "minVersion");
            return (Criteria) this;
        }

        public Criteria andMinVersionLessThanOrEqualTo(String value) {
            addCriterion("min_version <=", value, "minVersion");
            return (Criteria) this;
        }

        public Criteria andMinVersionLike(String value) {
            addCriterion("min_version like", value, "minVersion");
            return (Criteria) this;
        }

        public Criteria andMinVersionNotLike(String value) {
            addCriterion("min_version not like", value, "minVersion");
            return (Criteria) this;
        }

        public Criteria andMinVersionIn(List<String> values) {
            addCriterion("min_version in", values, "minVersion");
            return (Criteria) this;
        }

        public Criteria andMinVersionNotIn(List<String> values) {
            addCriterion("min_version not in", values, "minVersion");
            return (Criteria) this;
        }

        public Criteria andMinVersionBetween(String value1, String value2) {
            addCriterion("min_version between", value1, value2, "minVersion");
            return (Criteria) this;
        }

        public Criteria andMinVersionNotBetween(String value1, String value2) {
            addCriterion("min_version not between", value1, value2, "minVersion");
            return (Criteria) this;
        }

        public Criteria andMinVersionFixIsNull() {
            addCriterion("min_version_fix is null");
            return (Criteria) this;
        }

        public Criteria andMinVersionFixIsNotNull() {
            addCriterion("min_version_fix is not null");
            return (Criteria) this;
        }

        public Criteria andMinVersionFixEqualTo(String value) {
            addCriterion("min_version_fix =", value, "minVersionFix");
            return (Criteria) this;
        }

        public Criteria andMinVersionFixNotEqualTo(String value) {
            addCriterion("min_version_fix <>", value, "minVersionFix");
            return (Criteria) this;
        }

        public Criteria andMinVersionFixGreaterThan(String value) {
            addCriterion("min_version_fix >", value, "minVersionFix");
            return (Criteria) this;
        }

        public Criteria andMinVersionFixGreaterThanOrEqualTo(String value) {
            addCriterion("min_version_fix >=", value, "minVersionFix");
            return (Criteria) this;
        }

        public Criteria andMinVersionFixLessThan(String value) {
            addCriterion("min_version_fix <", value, "minVersionFix");
            return (Criteria) this;
        }

        public Criteria andMinVersionFixLessThanOrEqualTo(String value) {
            addCriterion("min_version_fix <=", value, "minVersionFix");
            return (Criteria) this;
        }

        public Criteria andMinVersionFixLike(String value) {
            addCriterion("min_version_fix like", value, "minVersionFix");
            return (Criteria) this;
        }

        public Criteria andMinVersionFixNotLike(String value) {
            addCriterion("min_version_fix not like", value, "minVersionFix");
            return (Criteria) this;
        }

        public Criteria andMinVersionFixIn(List<String> values) {
            addCriterion("min_version_fix in", values, "minVersionFix");
            return (Criteria) this;
        }

        public Criteria andMinVersionFixNotIn(List<String> values) {
            addCriterion("min_version_fix not in", values, "minVersionFix");
            return (Criteria) this;
        }

        public Criteria andMinVersionFixBetween(String value1, String value2) {
            addCriterion("min_version_fix between", value1, value2, "minVersionFix");
            return (Criteria) this;
        }

        public Criteria andMinVersionFixNotBetween(String value1, String value2) {
            addCriterion("min_version_fix not between", value1, value2, "minVersionFix");
            return (Criteria) this;
        }

        public Criteria andMaxVersionIsNull() {
            addCriterion("max_version is null");
            return (Criteria) this;
        }

        public Criteria andMaxVersionIsNotNull() {
            addCriterion("max_version is not null");
            return (Criteria) this;
        }

        public Criteria andMaxVersionEqualTo(String value) {
            addCriterion("max_version =", value, "maxVersion");
            return (Criteria) this;
        }

        public Criteria andMaxVersionNotEqualTo(String value) {
            addCriterion("max_version <>", value, "maxVersion");
            return (Criteria) this;
        }

        public Criteria andMaxVersionGreaterThan(String value) {
            addCriterion("max_version >", value, "maxVersion");
            return (Criteria) this;
        }

        public Criteria andMaxVersionGreaterThanOrEqualTo(String value) {
            addCriterion("max_version >=", value, "maxVersion");
            return (Criteria) this;
        }

        public Criteria andMaxVersionLessThan(String value) {
            addCriterion("max_version <", value, "maxVersion");
            return (Criteria) this;
        }

        public Criteria andMaxVersionLessThanOrEqualTo(String value) {
            addCriterion("max_version <=", value, "maxVersion");
            return (Criteria) this;
        }

        public Criteria andMaxVersionLike(String value) {
            addCriterion("max_version like", value, "maxVersion");
            return (Criteria) this;
        }

        public Criteria andMaxVersionNotLike(String value) {
            addCriterion("max_version not like", value, "maxVersion");
            return (Criteria) this;
        }

        public Criteria andMaxVersionIn(List<String> values) {
            addCriterion("max_version in", values, "maxVersion");
            return (Criteria) this;
        }

        public Criteria andMaxVersionNotIn(List<String> values) {
            addCriterion("max_version not in", values, "maxVersion");
            return (Criteria) this;
        }

        public Criteria andMaxVersionBetween(String value1, String value2) {
            addCriterion("max_version between", value1, value2, "maxVersion");
            return (Criteria) this;
        }

        public Criteria andMaxVersionNotBetween(String value1, String value2) {
            addCriterion("max_version not between", value1, value2, "maxVersion");
            return (Criteria) this;
        }

        public Criteria andMaxVersionFixIsNull() {
            addCriterion("max_version_fix is null");
            return (Criteria) this;
        }

        public Criteria andMaxVersionFixIsNotNull() {
            addCriterion("max_version_fix is not null");
            return (Criteria) this;
        }

        public Criteria andMaxVersionFixEqualTo(String value) {
            addCriterion("max_version_fix =", value, "maxVersionFix");
            return (Criteria) this;
        }

        public Criteria andMaxVersionFixNotEqualTo(String value) {
            addCriterion("max_version_fix <>", value, "maxVersionFix");
            return (Criteria) this;
        }

        public Criteria andMaxVersionFixGreaterThan(String value) {
            addCriterion("max_version_fix >", value, "maxVersionFix");
            return (Criteria) this;
        }

        public Criteria andMaxVersionFixGreaterThanOrEqualTo(String value) {
            addCriterion("max_version_fix >=", value, "maxVersionFix");
            return (Criteria) this;
        }

        public Criteria andMaxVersionFixLessThan(String value) {
            addCriterion("max_version_fix <", value, "maxVersionFix");
            return (Criteria) this;
        }

        public Criteria andMaxVersionFixLessThanOrEqualTo(String value) {
            addCriterion("max_version_fix <=", value, "maxVersionFix");
            return (Criteria) this;
        }

        public Criteria andMaxVersionFixLike(String value) {
            addCriterion("max_version_fix like", value, "maxVersionFix");
            return (Criteria) this;
        }

        public Criteria andMaxVersionFixNotLike(String value) {
            addCriterion("max_version_fix not like", value, "maxVersionFix");
            return (Criteria) this;
        }

        public Criteria andMaxVersionFixIn(List<String> values) {
            addCriterion("max_version_fix in", values, "maxVersionFix");
            return (Criteria) this;
        }

        public Criteria andMaxVersionFixNotIn(List<String> values) {
            addCriterion("max_version_fix not in", values, "maxVersionFix");
            return (Criteria) this;
        }

        public Criteria andMaxVersionFixBetween(String value1, String value2) {
            addCriterion("max_version_fix between", value1, value2, "maxVersionFix");
            return (Criteria) this;
        }

        public Criteria andMaxVersionFixNotBetween(String value1, String value2) {
            addCriterion("max_version_fix not between", value1, value2, "maxVersionFix");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_version
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project_version
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}