package com.itrus.ukey.db;

import java.util.Date;

public class ProjectVersion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_version.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_version.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_version.is_push
     *
     * @mbggenerated
     */
    private Boolean isPush;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_version.product_version
     *
     * @mbggenerated
     */
    private Long productVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_version.project
     *
     * @mbggenerated
     */
    private Long project;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_version.min_version
     *
     * @mbggenerated
     */
    private String minVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_version.min_version_fix
     *
     * @mbggenerated
     */
    private String minVersionFix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_version.max_version
     *
     * @mbggenerated
     */
    private String maxVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project_version.max_version_fix
     *
     * @mbggenerated
     */
    private String maxVersionFix;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_version.id
     *
     * @return the value of project_version.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_version.id
     *
     * @param id the value for project_version.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_version.create_time
     *
     * @return the value of project_version.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_version.create_time
     *
     * @param createTime the value for project_version.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_version.is_push
     *
     * @return the value of project_version.is_push
     *
     * @mbggenerated
     */
    public Boolean getIsPush() {
        return isPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_version.is_push
     *
     * @param isPush the value for project_version.is_push
     *
     * @mbggenerated
     */
    public void setIsPush(Boolean isPush) {
        this.isPush = isPush;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_version.product_version
     *
     * @return the value of project_version.product_version
     *
     * @mbggenerated
     */
    public Long getProductVersion() {
        return productVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_version.product_version
     *
     * @param productVersion the value for project_version.product_version
     *
     * @mbggenerated
     */
    public void setProductVersion(Long productVersion) {
        this.productVersion = productVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_version.project
     *
     * @return the value of project_version.project
     *
     * @mbggenerated
     */
    public Long getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_version.project
     *
     * @param project the value for project_version.project
     *
     * @mbggenerated
     */
    public void setProject(Long project) {
        this.project = project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_version.min_version
     *
     * @return the value of project_version.min_version
     *
     * @mbggenerated
     */
    public String getMinVersion() {
        return minVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_version.min_version
     *
     * @param minVersion the value for project_version.min_version
     *
     * @mbggenerated
     */
    public void setMinVersion(String minVersion) {
        this.minVersion = minVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_version.min_version_fix
     *
     * @return the value of project_version.min_version_fix
     *
     * @mbggenerated
     */
    public String getMinVersionFix() {
        return minVersionFix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_version.min_version_fix
     *
     * @param minVersionFix the value for project_version.min_version_fix
     *
     * @mbggenerated
     */
    public void setMinVersionFix(String minVersionFix) {
        this.minVersionFix = minVersionFix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_version.max_version
     *
     * @return the value of project_version.max_version
     *
     * @mbggenerated
     */
    public String getMaxVersion() {
        return maxVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_version.max_version
     *
     * @param maxVersion the value for project_version.max_version
     *
     * @mbggenerated
     */
    public void setMaxVersion(String maxVersion) {
        this.maxVersion = maxVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project_version.max_version_fix
     *
     * @return the value of project_version.max_version_fix
     *
     * @mbggenerated
     */
    public String getMaxVersionFix() {
        return maxVersionFix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project_version.max_version_fix
     *
     * @param maxVersionFix the value for project_version.max_version_fix
     *
     * @mbggenerated
     */
    public void setMaxVersionFix(String maxVersionFix) {
        this.maxVersionFix = maxVersionFix;
    }
}