package com.itrus.ukey.db;

import java.util.Date;

public class SmsGate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_gate.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_gate.account_name
     *
     * @mbggenerated
     */
    private String accountName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_gate.account_pass
     *
     * @mbggenerated
     */
    private String accountPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_gate.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_gate.gate_address
     *
     * @mbggenerated
     */
    private String gateAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_gate.md5_key
     *
     * @mbggenerated
     */
    private String md5Key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_gate.last_modify
     *
     * @mbggenerated
     */
    private Date lastModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_gate.gate_type
     *
     * @mbggenerated
     */
    private Integer gateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_gate.emay_address
     *
     * @mbggenerated
     */
    private String emayAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_gate.emay_pass
     *
     * @mbggenerated
     */
    private String emayPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_gate.emay_serialnum
     *
     * @mbggenerated
     */
    private String emaySerialnum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_gate.id
     *
     * @return the value of sms_gate.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_gate.id
     *
     * @param id the value for sms_gate.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_gate.account_name
     *
     * @return the value of sms_gate.account_name
     *
     * @mbggenerated
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_gate.account_name
     *
     * @param accountName the value for sms_gate.account_name
     *
     * @mbggenerated
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_gate.account_pass
     *
     * @return the value of sms_gate.account_pass
     *
     * @mbggenerated
     */
    public String getAccountPass() {
        return accountPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_gate.account_pass
     *
     * @param accountPass the value for sms_gate.account_pass
     *
     * @mbggenerated
     */
    public void setAccountPass(String accountPass) {
        this.accountPass = accountPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_gate.create_time
     *
     * @return the value of sms_gate.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_gate.create_time
     *
     * @param createTime the value for sms_gate.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_gate.gate_address
     *
     * @return the value of sms_gate.gate_address
     *
     * @mbggenerated
     */
    public String getGateAddress() {
        return gateAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_gate.gate_address
     *
     * @param gateAddress the value for sms_gate.gate_address
     *
     * @mbggenerated
     */
    public void setGateAddress(String gateAddress) {
        this.gateAddress = gateAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_gate.md5_key
     *
     * @return the value of sms_gate.md5_key
     *
     * @mbggenerated
     */
    public String getMd5Key() {
        return md5Key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_gate.md5_key
     *
     * @param md5Key the value for sms_gate.md5_key
     *
     * @mbggenerated
     */
    public void setMd5Key(String md5Key) {
        this.md5Key = md5Key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_gate.last_modify
     *
     * @return the value of sms_gate.last_modify
     *
     * @mbggenerated
     */
    public Date getLastModify() {
        return lastModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_gate.last_modify
     *
     * @param lastModify the value for sms_gate.last_modify
     *
     * @mbggenerated
     */
    public void setLastModify(Date lastModify) {
        this.lastModify = lastModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_gate.gate_type
     *
     * @return the value of sms_gate.gate_type
     *
     * @mbggenerated
     */
    public Integer getGateType() {
        return gateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_gate.gate_type
     *
     * @param gateType the value for sms_gate.gate_type
     *
     * @mbggenerated
     */
    public void setGateType(Integer gateType) {
        this.gateType = gateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_gate.emay_address
     *
     * @return the value of sms_gate.emay_address
     *
     * @mbggenerated
     */
    public String getEmayAddress() {
        return emayAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_gate.emay_address
     *
     * @param emayAddress the value for sms_gate.emay_address
     *
     * @mbggenerated
     */
    public void setEmayAddress(String emayAddress) {
        this.emayAddress = emayAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_gate.emay_pass
     *
     * @return the value of sms_gate.emay_pass
     *
     * @mbggenerated
     */
    public String getEmayPass() {
        return emayPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_gate.emay_pass
     *
     * @param emayPass the value for sms_gate.emay_pass
     *
     * @mbggenerated
     */
    public void setEmayPass(String emayPass) {
        this.emayPass = emayPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_gate.emay_serialnum
     *
     * @return the value of sms_gate.emay_serialnum
     *
     * @mbggenerated
     */
    public String getEmaySerialnum() {
        return emaySerialnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_gate.emay_serialnum
     *
     * @param emaySerialnum the value for sms_gate.emay_serialnum
     *
     * @mbggenerated
     */
    public void setEmaySerialnum(String emaySerialnum) {
        this.emaySerialnum = emaySerialnum;
    }
}