package com.itrus.ukey.db;

public class SysConfig {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_config.id
	 * @mbggenerated
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_config.config
	 * @mbggenerated
	 */
	private String config;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_config.type
	 * @mbggenerated
	 */
	private String type;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_config.id
	 * @return  the value of sys_config.id
	 * @mbggenerated
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_config.id
	 * @param id  the value for sys_config.id
	 * @mbggenerated
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_config.config
	 * @return  the value of sys_config.config
	 * @mbggenerated
	 */
	public String getConfig() {
		return config;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_config.config
	 * @param config  the value for sys_config.config
	 * @mbggenerated
	 */
	public void setConfig(String config) {
		this.config = config;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_config.type
	 * @return  the value of sys_config.type
	 * @mbggenerated
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_config.type
	 * @param type  the value for sys_config.type
	 * @mbggenerated
	 */
	public void setType(String type) {
		this.type = type;
	}
}