package com.itrus.ukey.db;

import java.util.ArrayList;
import java.util.List;

public class SysResourcesExample extends DomainSur {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_resources
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_resources
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_resources
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated
     */
    public SysResourcesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_resources
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_resources
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andParentNumIsNull() {
            addCriterion("parent_num is null");
            return (Criteria) this;
        }

        public Criteria andParentNumIsNotNull() {
            addCriterion("parent_num is not null");
            return (Criteria) this;
        }

        public Criteria andParentNumEqualTo(Integer value) {
            addCriterion("parent_num =", value, "parentNum");
            return (Criteria) this;
        }

        public Criteria andParentNumNotEqualTo(Integer value) {
            addCriterion("parent_num <>", value, "parentNum");
            return (Criteria) this;
        }

        public Criteria andParentNumGreaterThan(Integer value) {
            addCriterion("parent_num >", value, "parentNum");
            return (Criteria) this;
        }

        public Criteria andParentNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("parent_num >=", value, "parentNum");
            return (Criteria) this;
        }

        public Criteria andParentNumLessThan(Integer value) {
            addCriterion("parent_num <", value, "parentNum");
            return (Criteria) this;
        }

        public Criteria andParentNumLessThanOrEqualTo(Integer value) {
            addCriterion("parent_num <=", value, "parentNum");
            return (Criteria) this;
        }

        public Criteria andParentNumIn(List<Integer> values) {
            addCriterion("parent_num in", values, "parentNum");
            return (Criteria) this;
        }

        public Criteria andParentNumNotIn(List<Integer> values) {
            addCriterion("parent_num not in", values, "parentNum");
            return (Criteria) this;
        }

        public Criteria andParentNumBetween(Integer value1, Integer value2) {
            addCriterion("parent_num between", value1, value2, "parentNum");
            return (Criteria) this;
        }

        public Criteria andParentNumNotBetween(Integer value1, Integer value2) {
            addCriterion("parent_num not between", value1, value2, "parentNum");
            return (Criteria) this;
        }

        public Criteria andResNumIsNull() {
            addCriterion("res_num is null");
            return (Criteria) this;
        }

        public Criteria andResNumIsNotNull() {
            addCriterion("res_num is not null");
            return (Criteria) this;
        }

        public Criteria andResNumEqualTo(Integer value) {
            addCriterion("res_num =", value, "resNum");
            return (Criteria) this;
        }

        public Criteria andResNumNotEqualTo(Integer value) {
            addCriterion("res_num <>", value, "resNum");
            return (Criteria) this;
        }

        public Criteria andResNumGreaterThan(Integer value) {
            addCriterion("res_num >", value, "resNum");
            return (Criteria) this;
        }

        public Criteria andResNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("res_num >=", value, "resNum");
            return (Criteria) this;
        }

        public Criteria andResNumLessThan(Integer value) {
            addCriterion("res_num <", value, "resNum");
            return (Criteria) this;
        }

        public Criteria andResNumLessThanOrEqualTo(Integer value) {
            addCriterion("res_num <=", value, "resNum");
            return (Criteria) this;
        }

        public Criteria andResNumIn(List<Integer> values) {
            addCriterion("res_num in", values, "resNum");
            return (Criteria) this;
        }

        public Criteria andResNumNotIn(List<Integer> values) {
            addCriterion("res_num not in", values, "resNum");
            return (Criteria) this;
        }

        public Criteria andResNumBetween(Integer value1, Integer value2) {
            addCriterion("res_num between", value1, value2, "resNum");
            return (Criteria) this;
        }

        public Criteria andResNumNotBetween(Integer value1, Integer value2) {
            addCriterion("res_num not between", value1, value2, "resNum");
            return (Criteria) this;
        }

        public Criteria andResRoleNameIsNull() {
            addCriterion("res_role_name is null");
            return (Criteria) this;
        }

        public Criteria andResRoleNameIsNotNull() {
            addCriterion("res_role_name is not null");
            return (Criteria) this;
        }

        public Criteria andResRoleNameEqualTo(String value) {
            addCriterion("res_role_name =", value, "resRoleName");
            return (Criteria) this;
        }

        public Criteria andResRoleNameNotEqualTo(String value) {
            addCriterion("res_role_name <>", value, "resRoleName");
            return (Criteria) this;
        }

        public Criteria andResRoleNameGreaterThan(String value) {
            addCriterion("res_role_name >", value, "resRoleName");
            return (Criteria) this;
        }

        public Criteria andResRoleNameGreaterThanOrEqualTo(String value) {
            addCriterion("res_role_name >=", value, "resRoleName");
            return (Criteria) this;
        }

        public Criteria andResRoleNameLessThan(String value) {
            addCriterion("res_role_name <", value, "resRoleName");
            return (Criteria) this;
        }

        public Criteria andResRoleNameLessThanOrEqualTo(String value) {
            addCriterion("res_role_name <=", value, "resRoleName");
            return (Criteria) this;
        }

        public Criteria andResRoleNameLike(String value) {
            addCriterion("res_role_name like", value, "resRoleName");
            return (Criteria) this;
        }

        public Criteria andResRoleNameNotLike(String value) {
            addCriterion("res_role_name not like", value, "resRoleName");
            return (Criteria) this;
        }

        public Criteria andResRoleNameIn(List<String> values) {
            addCriterion("res_role_name in", values, "resRoleName");
            return (Criteria) this;
        }

        public Criteria andResRoleNameNotIn(List<String> values) {
            addCriterion("res_role_name not in", values, "resRoleName");
            return (Criteria) this;
        }

        public Criteria andResRoleNameBetween(String value1, String value2) {
            addCriterion("res_role_name between", value1, value2, "resRoleName");
            return (Criteria) this;
        }

        public Criteria andResRoleNameNotBetween(String value1, String value2) {
            addCriterion("res_role_name not between", value1, value2, "resRoleName");
            return (Criteria) this;
        }

        public Criteria andResTitleIsNull() {
            addCriterion("res_title is null");
            return (Criteria) this;
        }

        public Criteria andResTitleIsNotNull() {
            addCriterion("res_title is not null");
            return (Criteria) this;
        }

        public Criteria andResTitleEqualTo(String value) {
            addCriterion("res_title =", value, "resTitle");
            return (Criteria) this;
        }

        public Criteria andResTitleNotEqualTo(String value) {
            addCriterion("res_title <>", value, "resTitle");
            return (Criteria) this;
        }

        public Criteria andResTitleGreaterThan(String value) {
            addCriterion("res_title >", value, "resTitle");
            return (Criteria) this;
        }

        public Criteria andResTitleGreaterThanOrEqualTo(String value) {
            addCriterion("res_title >=", value, "resTitle");
            return (Criteria) this;
        }

        public Criteria andResTitleLessThan(String value) {
            addCriterion("res_title <", value, "resTitle");
            return (Criteria) this;
        }

        public Criteria andResTitleLessThanOrEqualTo(String value) {
            addCriterion("res_title <=", value, "resTitle");
            return (Criteria) this;
        }

        public Criteria andResTitleLike(String value) {
            addCriterion("res_title like", value, "resTitle");
            return (Criteria) this;
        }

        public Criteria andResTitleNotLike(String value) {
            addCriterion("res_title not like", value, "resTitle");
            return (Criteria) this;
        }

        public Criteria andResTitleIn(List<String> values) {
            addCriterion("res_title in", values, "resTitle");
            return (Criteria) this;
        }

        public Criteria andResTitleNotIn(List<String> values) {
            addCriterion("res_title not in", values, "resTitle");
            return (Criteria) this;
        }

        public Criteria andResTitleBetween(String value1, String value2) {
            addCriterion("res_title between", value1, value2, "resTitle");
            return (Criteria) this;
        }

        public Criteria andResTitleNotBetween(String value1, String value2) {
            addCriterion("res_title not between", value1, value2, "resTitle");
            return (Criteria) this;
        }

        public Criteria andResUriIsNull() {
            addCriterion("res_uri is null");
            return (Criteria) this;
        }

        public Criteria andResUriIsNotNull() {
            addCriterion("res_uri is not null");
            return (Criteria) this;
        }

        public Criteria andResUriEqualTo(String value) {
            addCriterion("res_uri =", value, "resUri");
            return (Criteria) this;
        }

        public Criteria andResUriNotEqualTo(String value) {
            addCriterion("res_uri <>", value, "resUri");
            return (Criteria) this;
        }

        public Criteria andResUriGreaterThan(String value) {
            addCriterion("res_uri >", value, "resUri");
            return (Criteria) this;
        }

        public Criteria andResUriGreaterThanOrEqualTo(String value) {
            addCriterion("res_uri >=", value, "resUri");
            return (Criteria) this;
        }

        public Criteria andResUriLessThan(String value) {
            addCriterion("res_uri <", value, "resUri");
            return (Criteria) this;
        }

        public Criteria andResUriLessThanOrEqualTo(String value) {
            addCriterion("res_uri <=", value, "resUri");
            return (Criteria) this;
        }

        public Criteria andResUriLike(String value) {
            addCriterion("res_uri like", value, "resUri");
            return (Criteria) this;
        }

        public Criteria andResUriNotLike(String value) {
            addCriterion("res_uri not like", value, "resUri");
            return (Criteria) this;
        }

        public Criteria andResUriIn(List<String> values) {
            addCriterion("res_uri in", values, "resUri");
            return (Criteria) this;
        }

        public Criteria andResUriNotIn(List<String> values) {
            addCriterion("res_uri not in", values, "resUri");
            return (Criteria) this;
        }

        public Criteria andResUriBetween(String value1, String value2) {
            addCriterion("res_uri between", value1, value2, "resUri");
            return (Criteria) this;
        }

        public Criteria andResUriNotBetween(String value1, String value2) {
            addCriterion("res_uri not between", value1, value2, "resUri");
            return (Criteria) this;
        }

        public Criteria andResOrderIsNull() {
            addCriterion("res_order is null");
            return (Criteria) this;
        }

        public Criteria andResOrderIsNotNull() {
            addCriterion("res_order is not null");
            return (Criteria) this;
        }

        public Criteria andResOrderEqualTo(Integer value) {
            addCriterion("res_order =", value, "resOrder");
            return (Criteria) this;
        }

        public Criteria andResOrderNotEqualTo(Integer value) {
            addCriterion("res_order <>", value, "resOrder");
            return (Criteria) this;
        }

        public Criteria andResOrderGreaterThan(Integer value) {
            addCriterion("res_order >", value, "resOrder");
            return (Criteria) this;
        }

        public Criteria andResOrderGreaterThanOrEqualTo(Integer value) {
            addCriterion("res_order >=", value, "resOrder");
            return (Criteria) this;
        }

        public Criteria andResOrderLessThan(Integer value) {
            addCriterion("res_order <", value, "resOrder");
            return (Criteria) this;
        }

        public Criteria andResOrderLessThanOrEqualTo(Integer value) {
            addCriterion("res_order <=", value, "resOrder");
            return (Criteria) this;
        }

        public Criteria andResOrderIn(List<Integer> values) {
            addCriterion("res_order in", values, "resOrder");
            return (Criteria) this;
        }

        public Criteria andResOrderNotIn(List<Integer> values) {
            addCriterion("res_order not in", values, "resOrder");
            return (Criteria) this;
        }

        public Criteria andResOrderBetween(Integer value1, Integer value2) {
            addCriterion("res_order between", value1, value2, "resOrder");
            return (Criteria) this;
        }

        public Criteria andResOrderNotBetween(Integer value1, Integer value2) {
            addCriterion("res_order not between", value1, value2, "resOrder");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_resources
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_resources
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}