package com.itrus.ukey.db;

import java.util.Date;

public class SysUserCertLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_cert_log.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_cert_log.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_cert_log.project_id
     *
     * @mbggenerated
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_cert_log.sys_user
     *
     * @mbggenerated
     */
    private Long sysUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_cert_log.user_cert_id
     *
     * @mbggenerated
     */
    private Long userCertId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user_cert_log.user_device_id
     *
     * @mbggenerated
     */
    private Long userDeviceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_cert_log.id
     *
     * @return the value of sys_user_cert_log.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_cert_log.id
     *
     * @param id the value for sys_user_cert_log.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_cert_log.create_time
     *
     * @return the value of sys_user_cert_log.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_cert_log.create_time
     *
     * @param createTime the value for sys_user_cert_log.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_cert_log.project_id
     *
     * @return the value of sys_user_cert_log.project_id
     *
     * @mbggenerated
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_cert_log.project_id
     *
     * @param projectId the value for sys_user_cert_log.project_id
     *
     * @mbggenerated
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_cert_log.sys_user
     *
     * @return the value of sys_user_cert_log.sys_user
     *
     * @mbggenerated
     */
    public Long getSysUser() {
        return sysUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_cert_log.sys_user
     *
     * @param sysUser the value for sys_user_cert_log.sys_user
     *
     * @mbggenerated
     */
    public void setSysUser(Long sysUser) {
        this.sysUser = sysUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_cert_log.user_cert_id
     *
     * @return the value of sys_user_cert_log.user_cert_id
     *
     * @mbggenerated
     */
    public Long getUserCertId() {
        return userCertId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_cert_log.user_cert_id
     *
     * @param userCertId the value for sys_user_cert_log.user_cert_id
     *
     * @mbggenerated
     */
    public void setUserCertId(Long userCertId) {
        this.userCertId = userCertId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user_cert_log.user_device_id
     *
     * @return the value of sys_user_cert_log.user_device_id
     *
     * @mbggenerated
     */
    public Long getUserDeviceId() {
        return userDeviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user_cert_log.user_device_id
     *
     * @param userDeviceId the value for sys_user_cert_log.user_device_id
     *
     * @mbggenerated
     */
    public void setUserDeviceId(Long userDeviceId) {
        this.userDeviceId = userDeviceId;
    }
}