package com.itrus.ukey.db;

import java.util.Date;

public class SysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generlator.
     * This field corresponds to the database column sys_user.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.entity_name
     *
     * @mbggenerated
     */
    private String entityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.last_modify
     *
     * @mbggenerated
     */
    private Date lastModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.m_phone
     *
     * @mbggenerated
     */
    private String mPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.org_industry
     *
     * @mbggenerated
     */
    private Integer orgIndustry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.postal_code
     *
     * @mbggenerated
     */
    private String postalCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.telephone
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.trust_email
     *
     * @mbggenerated
     */
    private Boolean trustEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.trust_m_phone
     *
     * @mbggenerated
     */
    private Boolean trustMPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.unique_id
     *
     * @mbggenerated
     */
    private String uniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_adds
     *
     * @mbggenerated
     */
    private String userAdds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.entity_true
     *
     * @mbggenerated
     */
    private Long entityTrue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.cert_id
     *
     * @mbggenerated
     */
    private Long certId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.project
     *
     * @mbggenerated
     */
    private Long project;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.region_codes
     *
     * @mbggenerated
     */
    private String regionCodes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_type
     *
     * @mbggenerated
     */
    private String userType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id
     *
     * @return the value of sys_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id
     *
     * @param id the value for sys_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.create_time
     *
     * @return the value of sys_user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.create_time
     *
     * @param createTime the value for sys_user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.email
     *
     * @return the value of sys_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.email
     *
     * @param email the value for sys_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.entity_name
     *
     * @return the value of sys_user.entity_name
     *
     * @mbggenerated
     */
    public String getEntityName() {
        return entityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.entity_name
     *
     * @param entityName the value for sys_user.entity_name
     *
     * @mbggenerated
     */
    public void setEntityName(String entityName) {
        this.entityName = entityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.last_modify
     *
     * @return the value of sys_user.last_modify
     *
     * @mbggenerated
     */
    public Date getLastModify() {
        return lastModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.last_modify
     *
     * @param lastModify the value for sys_user.last_modify
     *
     * @mbggenerated
     */
    public void setLastModify(Date lastModify) {
        this.lastModify = lastModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.m_phone
     *
     * @return the value of sys_user.m_phone
     *
     * @mbggenerated
     */
    public String getmPhone() {
        return mPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.m_phone
     *
     * @param mPhone the value for sys_user.m_phone
     *
     * @mbggenerated
     */
    public void setmPhone(String mPhone) {
        this.mPhone = mPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.org_industry
     *
     * @return the value of sys_user.org_industry
     *
     * @mbggenerated
     */
    public Integer getOrgIndustry() {
        return orgIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.org_industry
     *
     * @param orgIndustry the value for sys_user.org_industry
     *
     * @mbggenerated
     */
    public void setOrgIndustry(Integer orgIndustry) {
        this.orgIndustry = orgIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.postal_code
     *
     * @return the value of sys_user.postal_code
     *
     * @mbggenerated
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.postal_code
     *
     * @param postalCode the value for sys_user.postal_code
     *
     * @mbggenerated
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.real_name
     *
     * @return the value of sys_user.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.real_name
     *
     * @param realName the value for sys_user.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.telephone
     *
     * @return the value of sys_user.telephone
     *
     * @mbggenerated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.telephone
     *
     * @param telephone the value for sys_user.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.trust_email
     *
     * @return the value of sys_user.trust_email
     *
     * @mbggenerated
     */
    public Boolean getTrustEmail() {
        return trustEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.trust_email
     *
     * @param trustEmail the value for sys_user.trust_email
     *
     * @mbggenerated
     */
    public void setTrustEmail(Boolean trustEmail) {
        this.trustEmail = trustEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.trust_m_phone
     *
     * @return the value of sys_user.trust_m_phone
     *
     * @mbggenerated
     */
    public Boolean getTrustMPhone() {
        return trustMPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.trust_m_phone
     *
     * @param trustMPhone the value for sys_user.trust_m_phone
     *
     * @mbggenerated
     */
    public void setTrustMPhone(Boolean trustMPhone) {
        this.trustMPhone = trustMPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.unique_id
     *
     * @return the value of sys_user.unique_id
     *
     * @mbggenerated
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.unique_id
     *
     * @param uniqueId the value for sys_user.unique_id
     *
     * @mbggenerated
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_adds
     *
     * @return the value of sys_user.user_adds
     *
     * @mbggenerated
     */
    public String getUserAdds() {
        return userAdds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_adds
     *
     * @param userAdds the value for sys_user.user_adds
     *
     * @mbggenerated
     */
    public void setUserAdds(String userAdds) {
        this.userAdds = userAdds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.entity_true
     *
     * @return the value of sys_user.entity_true
     *
     * @mbggenerated
     */
    public Long getEntityTrue() {
        return entityTrue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.entity_true
     *
     * @param entityTrue the value for sys_user.entity_true
     *
     * @mbggenerated
     */
    public void setEntityTrue(Long entityTrue) {
        this.entityTrue = entityTrue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.cert_id
     *
     * @return the value of sys_user.cert_id
     *
     * @mbggenerated
     */
    public Long getCertId() {
        return certId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.cert_id
     *
     * @param certId the value for sys_user.cert_id
     *
     * @mbggenerated
     */
    public void setCertId(Long certId) {
        this.certId = certId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.project
     *
     * @return the value of sys_user.project
     *
     * @mbggenerated
     */
    public Long getProject() {
        return project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.project
     *
     * @param project the value for sys_user.project
     *
     * @mbggenerated
     */
    public void setProject(Long project) {
        this.project = project;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.region_codes
     *
     * @return the value of sys_user.region_codes
     *
     * @mbggenerated
     */
    public String getRegionCodes() {
        return regionCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.region_codes
     *
     * @param regionCodes the value for sys_user.region_codes
     *
     * @mbggenerated
     */
    public void setRegionCodes(String regionCodes) {
        this.regionCodes = regionCodes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_type
     *
     * @return the value of sys_user.user_type
     *
     * @mbggenerated
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_type
     *
     * @param userType the value for sys_user.user_type
     *
     * @mbggenerated
     */
    public void setUserType(String userType) {
        this.userType = userType;
    }
}