package com.itrus.ukey.db;

import java.util.Date;

public class TaxRegisterCert {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_register_cert.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_register_cert.cert_no
     *
     * @mbggenerated
     */
    private String certNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_register_cert.certificate_name
     *
     * @mbggenerated
     */
    private String certificateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_register_cert.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_register_cert.entity_name
     *
     * @mbggenerated
     */
    private String entityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_register_cert.img_file
     *
     * @mbggenerated
     */
    private String imgFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_register_cert.img_file_hash
     *
     * @mbggenerated
     */
    private String imgFileHash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_register_cert.item_status
     *
     * @mbggenerated
     */
    private Integer itemStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_register_cert.last_modify
     *
     * @mbggenerated
     */
    private Date lastModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_register_cert.reg_type
     *
     * @mbggenerated
     */
    private String regType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_register_cert.entity_true
     *
     * @mbggenerated
     */
    private Long entityTrue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_register_cert.trust_log
     *
     * @mbggenerated
     */
    private Long trustLog;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_register_cert.id
     *
     * @return the value of tax_register_cert.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_register_cert.id
     *
     * @param id the value for tax_register_cert.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_register_cert.cert_no
     *
     * @return the value of tax_register_cert.cert_no
     *
     * @mbggenerated
     */
    public String getCertNo() {
        return certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_register_cert.cert_no
     *
     * @param certNo the value for tax_register_cert.cert_no
     *
     * @mbggenerated
     */
    public void setCertNo(String certNo) {
        this.certNo = certNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_register_cert.certificate_name
     *
     * @return the value of tax_register_cert.certificate_name
     *
     * @mbggenerated
     */
    public String getCertificateName() {
        return certificateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_register_cert.certificate_name
     *
     * @param certificateName the value for tax_register_cert.certificate_name
     *
     * @mbggenerated
     */
    public void setCertificateName(String certificateName) {
        this.certificateName = certificateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_register_cert.create_time
     *
     * @return the value of tax_register_cert.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_register_cert.create_time
     *
     * @param createTime the value for tax_register_cert.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_register_cert.entity_name
     *
     * @return the value of tax_register_cert.entity_name
     *
     * @mbggenerated
     */
    public String getEntityName() {
        return entityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_register_cert.entity_name
     *
     * @param entityName the value for tax_register_cert.entity_name
     *
     * @mbggenerated
     */
    public void setEntityName(String entityName) {
        this.entityName = entityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_register_cert.img_file
     *
     * @return the value of tax_register_cert.img_file
     *
     * @mbggenerated
     */
    public String getImgFile() {
        return imgFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_register_cert.img_file
     *
     * @param imgFile the value for tax_register_cert.img_file
     *
     * @mbggenerated
     */
    public void setImgFile(String imgFile) {
        this.imgFile = imgFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_register_cert.img_file_hash
     *
     * @return the value of tax_register_cert.img_file_hash
     *
     * @mbggenerated
     */
    public String getImgFileHash() {
        return imgFileHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_register_cert.img_file_hash
     *
     * @param imgFileHash the value for tax_register_cert.img_file_hash
     *
     * @mbggenerated
     */
    public void setImgFileHash(String imgFileHash) {
        this.imgFileHash = imgFileHash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_register_cert.item_status
     *
     * @return the value of tax_register_cert.item_status
     *
     * @mbggenerated
     */
    public Integer getItemStatus() {
        return itemStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_register_cert.item_status
     *
     * @param itemStatus the value for tax_register_cert.item_status
     *
     * @mbggenerated
     */
    public void setItemStatus(Integer itemStatus) {
        this.itemStatus = itemStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_register_cert.last_modify
     *
     * @return the value of tax_register_cert.last_modify
     *
     * @mbggenerated
     */
    public Date getLastModify() {
        return lastModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_register_cert.last_modify
     *
     * @param lastModify the value for tax_register_cert.last_modify
     *
     * @mbggenerated
     */
    public void setLastModify(Date lastModify) {
        this.lastModify = lastModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_register_cert.reg_type
     *
     * @return the value of tax_register_cert.reg_type
     *
     * @mbggenerated
     */
    public String getRegType() {
        return regType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_register_cert.reg_type
     *
     * @param regType the value for tax_register_cert.reg_type
     *
     * @mbggenerated
     */
    public void setRegType(String regType) {
        this.regType = regType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_register_cert.entity_true
     *
     * @return the value of tax_register_cert.entity_true
     *
     * @mbggenerated
     */
    public Long getEntityTrue() {
        return entityTrue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_register_cert.entity_true
     *
     * @param entityTrue the value for tax_register_cert.entity_true
     *
     * @mbggenerated
     */
    public void setEntityTrue(Long entityTrue) {
        this.entityTrue = entityTrue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_register_cert.trust_log
     *
     * @return the value of tax_register_cert.trust_log
     *
     * @mbggenerated
     */
    public Long getTrustLog() {
        return trustLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_register_cert.trust_log
     *
     * @param trustLog the value for tax_register_cert.trust_log
     *
     * @mbggenerated
     */
    public void setTrustLog(Long trustLog) {
        this.trustLog = trustLog;
    }
    
    @Override
    public String toString() {
    	return "税务登记证号码：" + certNo + "，税务登记证发证机构：" + certificateName;
    }
}